services:
  - type: web
    name: kundli-api
    env: node
    buildCommand: |
      npm install
      pip install -r requirements.txt
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    plan: free